#!/bin/sh

echo 80 > /sys/devices/platform/sony-laptop/battery_care_limiter

echo 1 > /sys/bus/usb/devices/usb1/power/autosuspend
echo 1 > /sys/bus/usb/devices/usb2/power/autosuspend
echo 1 > /sys/bus/usb/devices/usb3/power/autosuspend
echo 1 > /sys/bus/usb/devices/usb4/power/autosuspend

echo 1 > /sys/module/snd_hda_intel/parameters/power_save
echo 1 > /dev/dsp

echo 5 > /proc/sys/vm/laptop_mode
echo 0 > /proc/sys/kernel/nmi_watchdog

echo 1500 > /proc/sys/vm/dirty_writeback_centisecs

echo auto > /sys/bus/pci/devices/0000:00:00.0/power/control
echo auto > /sys/bus/pci/devices/0000:00:02.0/power/control
echo auto > /sys/bus/pci/devices/0000:00:16.0/power/control
echo auto > /sys/bus/pci/devices/0000:00:1a.0/power/control
echo auto > /sys/bus/pci/devices/0000:00:1b.0/power/control
echo auto > /sys/bus/pci/devices/0000:00:1c.0/power/control
echo auto > /sys/bus/pci/devices/0000:00:1c.1/power/control
echo auto > /sys/bus/pci/devices/0000:00:1c.2/power/control
echo auto > /sys/bus/pci/devices/0000:00:1c.3/power/control
echo auto > /sys/bus/pci/devices/0000:00:1c.6/power/control
echo auto > /sys/bus/pci/devices/0000:00:1d.0/power/control
echo auto > /sys/bus/pci/devices/0000:00:1f.2/power/control
echo auto > /sys/bus/pci/devices/0000:00:1f.3/power/control
echo auto > /sys/bus/pci/devices/0000:02:00.0/power/control
echo auto > /sys/bus/pci/devices/0000:03:00.0/power/control
# echo auto > /sys/bus/pci/devices/0000:04:00.0/power/control
echo auto > /sys/bus/pci/devices/0000:05:00.0/power/control

echo min_power > /sys/class/scsi_host/host0/link_power_management_policy
echo min_power > /sys/class/scsi_host/host1/link_power_management_policy
echo min_power > /sys/class/scsi_host/host2/link_power_management_policy
echo min_power > /sys/class/scsi_host/host3/link_power_management_policy
echo min_power > /sys/class/scsi_host/host4/link_power_management_policy
echo min_power > /sys/class/scsi_host/host5/link_power_management_policy

